### ISSUE TITLE
Layout issue

### ISSUE THREAD

**Issue by Janhouse** [Rayzeq/quick-settings-audio-panel#20]
Today I reallized I can drag quick settings menu items around, and the volume control box has bigger box than it should be.

https://github.com/Rayzeq/quick-settings-audio-panel/assets/1036439/0c84b1d8-f211-40ca-b260-b12604911286

**Comment by Rayzeq** [comment]
Yeah, it's a feature of the latest version that is not yet on e.g.o.
I was aware of this bug, but had no idea what was causing it. I've found a fix, but I still have no idea what caused it.
Note that buggy panels will still have a small margin at the bottom because the root cause is not fixed.

**Comment by Rayzeq** [comment]
This is now fully fixed. It turns out that it was caused by a bug in Clutter (or an inconsistency, I don't really know).

**Comment by Janhouse** [comment]
Worked fine but then my PC went to sleep, locked screen, and after waking it up, this happened. 
![image](https://github.com/Rayzeq/quick-settings-audio-panel/assets/1036439/352719dc-55d0-4f92-b001-5378e0502587)

**Comment by Rayzeq** [comment]
Are you on version 21? This issue should have been corrected in this version (and it also should have been partially fixed in version 20).
If your already on version 21, can you run the following code in [looking glass](https://gjs.guide/extensions/development/debugging.html#looking-glass) (you can copy-paste the whole block):
```js
function recurs(trace, widget) {
	trace += " -> " + widget.toString();

	if (!widget.needs_expand(Clutter.Orientation.VERTICAL)) return;
	if (widget.y_expand) {
		console.log(`[DEBUG LOGS] ${trace}`);
		return;
	}

	for (const child of widget.get_children()) {
		recurs(trace, child);
	}
}
recurs('', Main.panel._libpanel._main_panel);
```
This should give you one or more lines starting with `[DEBUG LOGS]` in the logs (`journalctl -f -o cat /usr/bin/gnome-shell` to see the logs). Send those lines here so that I can try to understand the issue.
