### ISSUE TITLE
how to install quick-settings-audio-panel on ubuntu 22.04

### ISSUE THREAD

**Issue by mostafasamirs** [Rayzeq/quick-settings-audio-panel#4]

**Comment by Rayzeq** [comment]
As far as I know, Ubuntu 22.04 ships with gnome shell 42.x. This extension **does not** work for this version of gnome shell.
However, if you have upgraded to gnome shell 43 or 44 and need to install the extension manually, here's how to do it:
 * Download the [lastest version](https://github.com/Rayzeq/quick-settings-audio-panel/releases)
 * Extract the zip archive you just downloaded in `~/.local/share/gnome-shell/extensions`
 * Rename the extracted folder to `quick-settings-audio-panel@rayzeq.github.io`
 * Restart gnome shell (the easiest way is to log out and log back in)

**Comment by mostafasamirs** [comment]
when restarting gnome-shell ubuntu? Why

![Screenshot from 2023-05-15 22-05-41](https://github.com/Rayzeq/quick-settings-audio-panel/assets/60698500/43072bc3-b3e8-48d8-b9a2-2e8951e883d9)

**Comment by Rayzeq** [comment]
I don't know ¯\\\_(ツ)\_/¯
Please send the output of `gnome-shell --version`.
If you see that the version number is not 43 or 44, then you have an older version that's not supported (and it won't be because it's too different from the newer versions).

If your version is 43 or 44, a good help would be to send the gnome shell logs, to do this run `journalctl -f -o cat /usr/bin/gnome-shell > "~/gnome-logs.log"` in a terminal, enable the extension and restart gnome shell (press `Alt-F2` type `restart` and press enter). Once it has crashed, do whatever you did to return to a working session. Then attach the `gnome-logs.log` file (which will be in your home folder) to your message.

**Comment by Rayzeq** [comment]
Well, I think the best way to get the latest version of gnome shell would be upgrade to Ubuntu 22.10 or 23.04. If you don't want to upgrade your Ubuntu version you may be able to manually upgrade your gnome shell version but I doubt it's a good idea.

**Comment by mostafasamirs** [comment]
When is it support Ubuntu 22.04?

**Comment by Rayzeq** [comment]
Support for Ubuntu 22.04 is not planned as there are many internal differences between 42.x and 43, which means I would have to completely rewrite the extension to support it.
However, other extensions can replace some of its functionality:
  - per-app mixer: [Application Volume Mixer](https://extensions.gnome.org/extension/3499/application-volume-mixer/) (you can search for `mixer` to find more)
  - media controls: [MPRIS Panel Player](https://extensions.gnome.org/extension/4088/mpris-panel-player/) (you can search for `mpris` to find more)

**Comment by mostafasamirs** [comment]
thank you
