### ISSUE TITLE
Not able to change audio output from application mixer

### ISSUE THREAD

**Issue by AxelSkye** [Rayzeq/quick-settings-audio-panel#43]
If I open de main audio mixer, I can change the global audio output, but they are not displayed on the application mixer.
![Captura desde 2024-05-13 09-50-53](https://github.com/Rayzeq/quick-settings-audio-panel/assets/31951244/0e0e063d-17b0-4cf5-b206-de4d3b6b3fc1)
![Captura desde 2024-05-13 09-50-44](https://github.com/Rayzeq/quick-settings-audio-panel/assets/31951244/bb4b392a-c9cb-4eb1-89ce-e645254227f5)

**Comment by Rayzeq** [comment]
Could you tell me what do they look like in [pavucontrol](https://manpages.ubuntu.com/manpages/focal/man1/pavucontrol.1.html) ?

Here's an example of what you can have:
![image](https://github.com/Rayzeq/quick-settings-audio-panel/assets/26172375/5375b779-1ad3-46f2-805c-7ba4a02729c7)

Devices that are alternatives listed under “Port:” (`Analog Output / Amplifier` and `Analog Output / No Amplifier` in my screenshot) cannot be used by multiple applications at the same time (because they are multiple ports on the same sound card), so they don't appear in the application mixer.
However, if they are separate devices (`Built-in Audio Analog Stereo` and `null-sink Audio/Sink sink` in my screenshot), they should appear in the application mixer (and I have no idea why they don't 😅). In that case, could send screenshots of the "Output Devices" and "Configuration" tabs of pavucontrol ?

**Comment by Rayzeq** [comment]
I've just remembered another (very likely) potential cause of this issue: you're probably missing `pactl`.
Despite its name, `pactl` (pulseaudio control) also works with pipewire.

**Comment by AxelSkye** [comment]
I could get the headphones displayed but not the multiple ports, what a pity. Neither could do it by attaching the HDMI monitor to the iGPU and the DP to the dGPU :(

**Comment by Rayzeq** [comment]
Unfortunately, this is a limitation of the sound card driver (probably even of the hardware itself), so there's nothing you can do about it - even an external application can't let you use both simultaneously.
