### ISSUE TITLE
[Bug?]: Output Volume Sliders move in sync

### ISSUE THREAD

**Issue by NA0341** [Rayzeq/quick-settings-audio-panel#48]
**Description:**
+ When »Create per-device volume sliders« is activated, the two available sliders move in sync when I move either of them.
+ Their names are »Headphones – Built-in Audio« (output slider) & »Built-in Audio Analog Stereo« when 3,5mm audio is inserted ~ and »Speakers – Built-in Audio« (output slider) & »Built-in Audio Analog Stereo« without it connected.
+ I find this confusing, because:
    + a) ~~their volume is not the same level - but changes at the same rate (relative movement)~~ it's just visual because the sliders are of different length in some views and 
    + b) both outputs have their own volume value stored - which I can change whenever one of the outputs is currently enabled.

I connected a USB - Soundcard and could move it's volume independently. Even while not active.
**My Guess:** either this extension or the GNOME Shell has a bug where these "preinstalled" interfaces get linked in this way.

If this is supposed to be this way:
I suggest you change the »Remove the output slider« into a »Don't show duplicate sliders« option.
Because while this setting would remove redundant input controls - it also removes the possibility to change the output interface!

And lastly: If this is supposed behaviour - there would still be an interface missing since I cannot change the volume of the Laptop Speakers and 3,5mm Jack at the same time.
I would need to manually switch the output interface before I can change it's volume.
Maybe you could make it so that the second slider changes the volume of the alternate output - which would otherwise not be accessible.

Here's a video demonstration of the above mentioned behaviour:
[Screencast from 2024-06-24 11-43-50.webm](https://github.com/Rayzeq/quick-settings-audio-panel/assets/26059513/b21effbb-f4a8-4441-bd44-12537f1cb765)

The video also shows the third entry from #49:
[Bug]: Playback Controls expand under the below Element when outfolded via the Button.

**Desktop Info:**
 - OS: Manjaro 
 - Gnome shell version: GNOME 46 on Wayland

**Comment by Rayzeq** [comment]
The current behavior is as expected. The reason you have two "duplicate" sliders is that there is one for the default output device (the master slider) and one for the specific device.
Their names are different because gnome shows the sound card port, whereas my extension doesn't (I changed my extension to match gnome's name).

> I suggest you change the »Remove the output slider« into a »Don't show duplicate sliders« option.

I'm not sure this would be very useful; if you have per-device sliders, you probably also change the output device per application, so you don't really need to change the default output device (I also don't know how I'd implement this without making the UI super confusing).

> And lastly: If this is supposed behaviour - there would still be an interface missing since I cannot change the volume of the Laptop Speakers and 3,5mm Jack at the same time.
> I would need to manually switch the output interface before I can change it's volume.

This is because these are not two different devices, but different ports on the same device. The pulseaudio API (which is also used when using pipewire) doesn't allow changing the volume of a specific port, but only of the device itself.
