### ISSUE TITLE
It freezez gnome

### ISSUE THREAD

**Issue by Bernard996** [Rayzeq/quick-settings-audio-panel#56]
It looks like the extension is the cause of the complete freezing of GNOME, at least on Manjaro. Here it is the post of the forum.
https://forum.manjaro.org/t/gnome-randomly-freezes/168242/6

I am on Manjaro with GNOME 46.4

**Comment by NA0341** [comment]
Did you make a test where you disable **only** quick-settings-audio-panel without changing anything else and GNOME doesn't freeze anymore?
If above is the case: Are Your tests reproducible?

I too use this extension since quite some time along with lots of other extensions ~ and I have no issues at all. Neighter performance nor stability (yes the menu does get a little laggy if there are tons of audio streams ~ but this isn't necessarily an issue with this extension).

One extension which causes lag, misbehaviour and potentially other issues for me is `Dash to Dock`. Especially the Mouse Cursor literally gets stuck for sometimes even more than a second.
I have it configured as a transparent bar at the left corner (see screenshot).


Below is the System Info of my DELL Latitude Laptop (2019)

## System Details Report

### Report details
- **Date generated:**                              2024-09-19 02:10:53

### Hardware Information:
- **Hardware Model:**                              Dell Inc. Latitude E5470
- **Memory:**                                      16,0 GiB
- **Processor:**                                   Intel® Core™ i5-6300HQ × 4
- **Graphics:**                                    Intel® HD Graphics 530 (SKL GT2)
- **Disk Capacity:**                               256,1 GB

### Software Information:
- **Firmware Version:**                            1.34.3
- **OS Name:**                                     Manjaro Linux
- **OS Build:**                                    rolling
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.1.106-1-MANJARO


Screenshot of Quick Settings Audio Panel (top right) & Dash to Dock (left corner):

![image](https://github.com/user-attachments/assets/cfd3f5f5-bbad-4a00-96fa-ba385eb4bcf9)


I wish You Good Luck and hope I could help 😊

**Comment by Rayzeq** [comment]
v61 might solve the issue, but I doubt it.
I've changed the only thing I can think of that might cause freezes (even though it's very unlikely to cause any), so if that doesn't solve the issue, I have no idea what might be the cause.

**Comment by Bernard996** [comment]
> v61 might solve the issue, but I doubt it. I've changed the only thing I can think of that might cause freezes (even though it's very unlikely to cause any), so if that doesn't solve the issue, I have no idea what might be the cause.

Is it already published? I can try and let you know

**Comment by Bernard996** [comment]
The weird thing is that it looks like it freezes Gnome only when there are one or more monitors attached (I am on a laptop), while it works fine otherwise. In my case In have two monitors, one attached via the HDMI port and one with the Thunderbolt one, maybe this can help

**Comment by Rayzeq** [comment]
That's strange that you have issues with multiple monitors, everything works fine when I use two monitors in virtualbox.
Is your main monitor (the one where the quick settings are) on one of the external monitors, is any of your external monitor hidpi ? I guess some of these monitor configuration may cause some obscure issues with the code.

Yes, v61 is released, the extension should be automatically updated to this version.
It's strange that you're having issues with multiple monitors, everything works fine when I use two monitors in virtualbox.
Is your main monitor (the one where the quick settings are) on one of the external monitors, or is one of your external monitors hidpi? I think some of these monitor configurations may cause obscure issues with the code.

**Comment by Bernard996** [comment]
I'm sorry to submitted this issue, somebody told me that your extension could have been the problem but apparently, even uninstalling it, I still have the freeze issue, so it could be something else. Thank you for your quick support anyway.
